### ISSUE TITLE
example 01 crashes on OS X if you close the windows using the red button

### ISSUE THREAD

**Issue by buzmeg** [unknownue/vulkan-tutorial-rust#7] opened 2019-06-15 07:33 UTC
$ cargo run --bin 01
    Finished dev [unoptimized + debuginfo] target(s) in 0.15s
     Running `target/debug/01`
<close window with red button>
Bus error: 10

**Comment by unknownue** [comment] 2019-06-15 16:36
Everything seems OK on my machine, both in debug and release mode.
Have you tried the latest SDK ?
Press the `ESC` should close the program as well, does it crash when pressing `ESC`?

**Comment by buzmeg** [comment] 2019-06-15 23:45
Yes, crashes with ESC as well.

**Comment by unknownue** [comment] 2019-06-16 01:04
There is a [bug issue](https://github.com/KhronosGroup/MoltenVK/issues/584) in MoltenVK v1.1.106 may make the program crash. It should be fixed with the release of SDK v1.1.108.
Have you tried the latest SDK?

**Comment by buzmeg** [comment] 2019-06-17 10:07
I have not.  Given the pointer, I will try to do so.

**Comment by unknownue** [comment] 2019-08-01 02:00
Since there is no response for a long time. I would close this issue. If this problem still reproduces, open the issue again.

**Closed as completed by unknownue** 2019-08-01 02:00 UTC

**Comment by buzmeg** [comment] 2019-08-07 07:01
Crashing seems to be gone as of vulkansdk 1.1.114.
