### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by Sorrien** [unknownue/vulkan-tutorial-rust#27] opened 2020-01-08 11:01 UTC
I cannot compile with stable or nightly with the following errors:
```
error[E0283]: type annotations needed: cannot resolve `_: std::convert::Into<winit::dpi::Size>`
  --> src\utility\window.rs:16:10
   |
16 |         .with_inner_size((width, height).into())
   |          ^^^^^^^^^^^^^^^

error[E0599]: no variant or associated item named `EventsCleared` found for type `winit::event::Event<'_, _>` in the current scope
  --> src\utility\window.rs:75:26
   |
75 |                 | Event::EventsCleared => {
   |                          ^^^^^^^^^^^^^
   |                          |
   |                          variant or associated item not found in `winit::event::Event<'_, _>`
   |                          help: there is a variant with a similar name: `MainEventsCleared`
```

**Comment by unknownue** [comment] 2020-01-09 11:18
This is caused by the API change of `winit v0.20.0`. It may take me some days to fix it.

**Comment by Sorrien** [comment] 2020-01-09 12:03
What version could I downgrade to fix it temporarily?

**Comment by unknownue** [comment] 2020-01-09 12:35
Sometime the version you specify in `Cargo.toml` may not match the actual version written in `Cargo.lock`. You can specify `winit` version to `0.20.0-alpha4`. The compilation is work for this version on my computer. If it doesn't work, try to specify other version from `0.20.0-alpha3` to `0.20.0-alpha6`.
```toml
[dependencies]
winit = "=0.20.0-alpha4"  # Use '=' to specify the exact version you want
```

**Comment by Sorrien** [comment] 2020-01-09 13:23
That worked for me

**Comment by unknownue** [comment] 2020-01-10 09:26
This issue should be fixed in https://github.com/unknownue/vulkan-tutorial-rust/commit/abceb29d6cbb906859d772075f4fafa5fb1e2c33.
If it still not compiles on your computer, open this issue again.

**Closed as completed by unknownue** 2020-01-10 09:26 UTC
Labels: bug
